// AUTH TYPES
export const LOGIN_SUCCES = "LOGIN_SUCCES";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCES = "REGISTER_SUCCES";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SET_ERROR_MSG = "SET_ERROR_MSG";
export const LOGOUT_SUCCES = "LOGOUT_SUCCES";
export const UPDATE_PROFILE_SUCCES = "UPDATE_PROFILE_SUCCES";


// CHAT TYPES
export const FETCH_CHATS = "FETCH_CHATS";
export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";
export const FRIENDS_ONLINE = "FRIENDS_ONLINE";
export const FRIEND_ONLINE = "FRIEND_ONLINE";
export const FRIEND_OFFLINE = "FRIEND_OFFLINE";
export const SET_SOCKET = "SET_SOCKET";
export const RECEIVED_MESSAGE = "RECEIVED_MESSAGE";
export const SENDER_TYPING = "SENDER_TYPING";
export const PAGINATE_MESSAGES = "PAGINATE_MESSAGES";
export const INCREMENT_SCROLL = "INCREMENT_SCROLL";
export const SET_NEW_CHAT = "SET_NEW_CHAT";